/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.MediaTracker;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author joshu
 */
public class Adopt extends javax.swing.JFrame {
    // for moving the frame
    private Point mouseDownCompCoords;
    
    private UserLoggedIn userLoggedIn;
    private LandingPage landingPage;
    private Adopt adopt;
    private Rehome rehome;
    
    /**
     * Creates new form Rehome
     */
    public Adopt(LandingPage landingPage, UserLoggedIn userLoggedIn) {
        initComponents();
        if(userLoggedIn != null) {
            this.userLoggedIn = userLoggedIn;
            rehome = userLoggedIn.getRehome();
            adopt = userLoggedIn.getAdopt();
        } else if(landingPage != null) {
            this.landingPage = landingPage;
            adopt = landingPage.getAdopt();
        }
        
        setVisible(true);
        
        // radio buttons
        workType.add(travel);
        workType.add(noTravel);
        
        petSex.add(male);
        petSex.add(female);
        
        petOrigin.add(owned);
        petOrigin.add(rescued);
        
        petStatus.add(adopted);
        petStatus.add(notAdopted);
        
        petSize.add(tiny);
        petSize.add(small);
        petSize.add(medium);
        petSize.add(large);
        
        // hide 2nd panel
        adoptPanel2.setVisible(false);
        
        // Window logo
        setWindowIcon();
    }
    
    public Adopt() {
        initComponents();
        
        // radio buttons
        workType.add(travel);
        workType.add(noTravel);
        
        petSex.add(male);
        petSex.add(female);
        
        petOrigin.add(owned);
        petOrigin.add(rescued);
        
        petStatus.add(adopted);
        petStatus.add(notAdopted);
        
        petSize.add(tiny);
        petSize.add(small);
        petSize.add(medium);
        petSize.add(large);
        
        // hide 2nd panel
        adoptPanel2.setVisible(false);
        
        // Window logo
        setWindowIcon();
    }
    
    private void setWindowIcon() {
        ImageIcon icon1 = null;
        try {
            icon1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/logo2.png")));
            if (icon1.getImageLoadStatus() == MediaTracker.ERRORED) {
                throw new NullPointerException("Image not found or cannot be loaded.");
            }
            this.setIconImage(icon1.getImage());
        } catch (NullPointerException e) {
            System.err.println("Error: Image not found. " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    // getters
    public Rehome getRehome() {
        return rehome;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workType = new javax.swing.ButtonGroup();
        petSex = new javax.swing.ButtonGroup();
        petOrigin = new javax.swing.ButtonGroup();
        petStatus = new javax.swing.ButtonGroup();
        petSize = new javax.swing.ButtonGroup();
        minimizeButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        rehomeButton = new javax.swing.JLabel();
        petButton = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        adoptPanel1 = new javax.swing.JPanel();
        adoptNext = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        adopterID = new javax.swing.JTextField();
        income = new javax.swing.JTextField();
        emailAddress = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        companyName = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        noTravel = new javax.swing.JCheckBox();
        travel = new javax.swing.JCheckBox();
        addressScroll = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        adopt1 = new javax.swing.JLabel();
        adoptPanel2 = new javax.swing.JPanel();
        adoptButton = new javax.swing.JLabel();
        adoptPrev = new javax.swing.JLabel();
        petAge = new javax.swing.JTextField();
        petType = new javax.swing.JTextField();
        petName = new javax.swing.JTextField();
        petID = new javax.swing.JTextField();
        adopted = new javax.swing.JCheckBox();
        notAdopted = new javax.swing.JCheckBox();
        rescued = new javax.swing.JCheckBox();
        owned = new javax.swing.JCheckBox();
        iAgree = new javax.swing.JCheckBox();
        large = new javax.swing.JCheckBox();
        medium = new javax.swing.JCheckBox();
        tiny = new javax.swing.JCheckBox();
        small = new javax.swing.JCheckBox();
        male = new javax.swing.JCheckBox();
        female = new javax.swing.JCheckBox();
        adopt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adopt");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize button (1).png"))); // NOI18N
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseExited(evt);
            }
        });
        getContentPane().add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 10, 40, 20));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back button (1).png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 5, 40, 40));

        rehomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app rehome button.png"))); // NOI18N
        rehomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rehomeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rehomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rehomeButtonMouseExited(evt);
            }
        });
        getContentPane().add(rehomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 175, -1, -1));

        petButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pet button (1).png"))); // NOI18N
        petButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                petButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                petButtonMouseExited(evt);
            }
        });
        getContentPane().add(petButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 175, -1, -1));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 110));

        adoptPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        adoptPanel1.setPreferredSize(new java.awt.Dimension(900, 680));
        adoptPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adoptNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app next button.png"))); // NOI18N
        adoptNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adoptNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adoptNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adoptNextMouseExited(evt);
            }
        });
        adoptPanel1.add(adoptNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 575, 220, 70));

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        adoptPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 324, 162, 32));
        adoptPanel1.add(adopterID, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 324, 354, 32));
        adoptPanel1.add(income, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 538, 278, 32));
        adoptPanel1.add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 424, 297, 32));
        adoptPanel1.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 424, 207, 32));

        occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationActionPerformed(evt);
            }
        });
        adoptPanel1.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 502, 562, 32));
        adoptPanel1.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 466, 517, 32));
        adoptPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 287, 232, 32));
        adoptPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 287, 238, 32));

        noTravel.setContentAreaFilled(false);
        noTravel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noTravel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adoptPanel1.add(noTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 545, 20, 20));

        travel.setContentAreaFilled(false);
        travel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        travel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adoptPanel1.add(travel, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 545, 20, 20));

        addressScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        address.setColumns(20);
        address.setRows(5);
        addressScroll.setViewportView(address);

        adoptPanel1.add(addressScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 360, 563, 59));

        adopt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ADOPT Fp1.png"))); // NOI18N
        adoptPanel1.add(adopt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 896, 676));

        getContentPane().add(adoptPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 680));

        adoptPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        adoptPanel2.setMinimumSize(new java.awt.Dimension(900, 680));
        adoptPanel2.setPreferredSize(new java.awt.Dimension(900, 680));
        adoptPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adoptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app adopt button.png"))); // NOI18N
        adoptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adoptButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adoptButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adoptButtonMouseExited(evt);
            }
        });
        adoptPanel2.add(adoptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 570, -1, -1));

        adoptPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app prev button.png"))); // NOI18N
        adoptPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adoptPrevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adoptPrevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adoptPrevMouseExited(evt);
            }
        });
        adoptPanel2.add(adoptPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 565, 220, 75));

        petAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petAgeActionPerformed(evt);
            }
        });
        adoptPanel2.add(petAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 323, 162, 32));

        petType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petTypeActionPerformed(evt);
            }
        });
        adoptPanel2.add(petType, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 358, 290, 32));

        petName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petNameActionPerformed(evt);
            }
        });
        adoptPanel2.add(petName, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 323, 362, 32));

        petID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petIDActionPerformed(evt);
            }
        });
        adoptPanel2.add(petID, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 287, 393, 32));

        adopted.setContentAreaFilled(false);
        adopted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adopted.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adopted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptedActionPerformed(evt);
            }
        });
        adoptPanel2.add(adopted, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 397, 20, 20));

        notAdopted.setContentAreaFilled(false);
        notAdopted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notAdopted.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notAdopted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notAdoptedActionPerformed(evt);
            }
        });
        adoptPanel2.add(notAdopted, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 397, 20, 20));

        rescued.setContentAreaFilled(false);
        rescued.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescued.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rescued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescuedActionPerformed(evt);
            }
        });
        adoptPanel2.add(rescued, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 364, 20, 20));

        owned.setContentAreaFilled(false);
        owned.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        owned.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        owned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownedActionPerformed(evt);
            }
        });
        adoptPanel2.add(owned, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 364, 20, 20));

        iAgree.setContentAreaFilled(false);
        iAgree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iAgree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAgreeActionPerformed(evt);
            }
        });
        adoptPanel2.add(iAgree, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 527, 20, 20));

        large.setContentAreaFilled(false);
        large.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        large.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeActionPerformed(evt);
            }
        });
        adoptPanel2.add(large, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 397, 20, 20));

        medium.setContentAreaFilled(false);
        medium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medium.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });
        adoptPanel2.add(medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 396, 20, 20));

        tiny.setContentAreaFilled(false);
        tiny.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiny.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tiny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinyActionPerformed(evt);
            }
        });
        adoptPanel2.add(tiny, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 397, 20, 20));

        small.setContentAreaFilled(false);
        small.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        small.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });
        adoptPanel2.add(small, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 396, 20, 20));

        male.setContentAreaFilled(false);
        male.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        male.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        adoptPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 291, 20, 20));

        female.setContentAreaFilled(false);
        female.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        female.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        adoptPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 291, 20, 20));

        adopt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ADOPT Fp2.png"))); // NOI18N
        adoptPanel2.add(adopt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 896, 676));

        getContentPane().add(adoptPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        // TODO add your handling code here:
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back button (1).png")));
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        // TODO add your handling code here:
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back button hover (1).png")));
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void minimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseExited
        // TODO add your handling code here:
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize button (1).png")));
    }//GEN-LAST:event_minimizeButtonMouseExited

    private void minimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseEntered
        // TODO add your handling code here:
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize button hover (1).png")));
    }//GEN-LAST:event_minimizeButtonMouseEntered

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        mouseDownCompCoords = evt.getPoint();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        Point currCoords = evt.getLocationOnScreen();
        setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
    }//GEN-LAST:event_headerMouseDragged

    private void adoptNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptNextMouseClicked
        // TODO add your handling code here:
        adoptPanel1.setVisible(false);
        adoptPanel2.setVisible(true);
    }//GEN-LAST:event_adoptNextMouseClicked

    private void adoptNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptNextMouseEntered
        // TODO add your handling code here:
        adoptNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app next button hover.png")));
    }//GEN-LAST:event_adoptNextMouseEntered

    private void adoptNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptNextMouseExited
        // TODO add your handling code here:
        adoptNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app next button.png")));
    }//GEN-LAST:event_adoptNextMouseExited

    private void adoptPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptPrevMouseClicked
        // TODO add your handling code here:
        adoptPanel1.setVisible(true);
        adoptPanel2.setVisible(false);
    }//GEN-LAST:event_adoptPrevMouseClicked

    private void adoptPrevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptPrevMouseEntered
        // TODO add your handling code here
        adoptPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app prev button hover.png")));
    }//GEN-LAST:event_adoptPrevMouseEntered

    private void adoptPrevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptPrevMouseExited
        // TODO add your handling code here:
        adoptPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app prev button.png")));
    }//GEN-LAST:event_adoptPrevMouseExited

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationActionPerformed

    private void petIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petIDActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void petAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petAgeActionPerformed

    private void petNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petNameActionPerformed

    private void petTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petTypeActionPerformed

    private void rescuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescuedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rescuedActionPerformed

    private void ownedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownedActionPerformed

    private void adoptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adoptedActionPerformed

    private void notAdoptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notAdoptedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notAdoptedActionPerformed

    private void tinyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinyActionPerformed

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallActionPerformed

    private void largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumActionPerformed

    private void iAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAgreeActionPerformed

    private void rehomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rehomeButtonMouseClicked
        // TODO add your handling code here:
        if (userLoggedIn != null) {
            rehome = userLoggedIn.getRehome();
        }
        if (rehome == null) {
            rehome = new Rehome(userLoggedIn);
            rehome.setVisible(true);
        } else if (!rehome.isVisible()) {
            rehome.setVisible(true);
        } else {
            rehome.toFront();
            rehome.requestFocus();
        }
        this.dispose();
    }//GEN-LAST:event_rehomeButtonMouseClicked

    private void rehomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rehomeButtonMouseEntered
        // TODO add your handling code here:
        rehomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app rehome button hover.png")));
    }//GEN-LAST:event_rehomeButtonMouseEntered

    private void rehomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rehomeButtonMouseExited
        // TODO add your handling code here:
        rehomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app rehome button.png")));
    }//GEN-LAST:event_rehomeButtonMouseExited

    private void petButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_petButtonMouseClicked

    private void petButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petButtonMouseEntered
        // TODO add your handling code here:
        petButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pet button hover (1).png")));
    }//GEN-LAST:event_petButtonMouseEntered

    private void petButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petButtonMouseExited
        // TODO add your handling code here:
        petButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pet button (1).png")));
    }//GEN-LAST:event_petButtonMouseExited

    private void adoptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adoptButtonMouseClicked

    private void adoptButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptButtonMouseEntered
        // TODO add your handling code here:
        adoptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app adopt button hover.png")));
    }//GEN-LAST:event_adoptButtonMouseEntered

    private void adoptButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptButtonMouseExited
        // TODO add your handling code here:
        adoptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/app adopt button.png")));
    }//GEN-LAST:event_adoptButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adopt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JScrollPane addressScroll;
    private javax.swing.JLabel adopt1;
    private javax.swing.JLabel adopt2;
    private javax.swing.JLabel adoptButton;
    private javax.swing.JLabel adoptNext;
    private javax.swing.JPanel adoptPanel1;
    private javax.swing.JPanel adoptPanel2;
    private javax.swing.JLabel adoptPrev;
    private javax.swing.JCheckBox adopted;
    private javax.swing.JTextField adopterID;
    private javax.swing.JTextField age;
    private javax.swing.JLabel backButton;
    private javax.swing.JTextField companyName;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JCheckBox female;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel header;
    private javax.swing.JCheckBox iAgree;
    private javax.swing.JTextField income;
    private javax.swing.JCheckBox large;
    private javax.swing.JTextField lastName;
    private javax.swing.JCheckBox male;
    private javax.swing.JCheckBox medium;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JCheckBox noTravel;
    private javax.swing.JCheckBox notAdopted;
    private javax.swing.JTextField occupation;
    private javax.swing.JCheckBox owned;
    private javax.swing.JTextField petAge;
    private javax.swing.JLabel petButton;
    private javax.swing.JTextField petID;
    private javax.swing.JTextField petName;
    private javax.swing.ButtonGroup petOrigin;
    private javax.swing.ButtonGroup petSex;
    private javax.swing.ButtonGroup petSize;
    private javax.swing.ButtonGroup petStatus;
    private javax.swing.JTextField petType;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JLabel rehomeButton;
    private javax.swing.JCheckBox rescued;
    private javax.swing.JCheckBox small;
    private javax.swing.JCheckBox tiny;
    private javax.swing.JCheckBox travel;
    private javax.swing.ButtonGroup workType;
    // End of variables declaration//GEN-END:variables
}
