/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.MediaTracker;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.concurrent.CountDownLatch;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author joshu
 */
public class InformationDialog extends javax.swing.JFrame {
    // for moving the frame
    private Point mouseDownCompCoords;
    
    // sub frames 
    Adopt adopt;
    Rehome rehome;
    Rescued rescued;
    
    private boolean userResponse;
    private JPanel glassPane = (JPanel) null;
    private final CountDownLatch latch;

    public InformationDialog(Adopt adopt, Rehome rehome, Rescued rescued, CountDownLatch latch) {
        initComponents();
        this.latch = latch;
        if(adopt != null) {
            this.glassPane = (JPanel) adopt.getGlassPane();
        } else if(rehome != null) {
            this.glassPane = (JPanel) rehome.getGlassPane();
        } else if(rescued != null) {
            this.glassPane = (JPanel) rescued.getGlassPane();
        }
        // Window logo
        try {
            ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/logo2.png")));
            if (icon.getImageLoadStatus() == MediaTracker.ERRORED) {
                throw new NullPointerException("Image not found or cannot be loaded.");
            }
            this.setIconImage(icon.getImage());
        } catch (NullPointerException e) {
            System.err.println("Error: Image not found. " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Getters and setters
    public boolean getUserResponse() {
        return userResponse;
    }

    public void setUserResponse(boolean userResponse) {
        this.userResponse = userResponse;
    }

    public JPanel getGlassPane() {
        return glassPane;
    }

    public JLabel getYesButton() {
        return yesButton;
    }

    public JLabel getNoButton() {
        return noButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        informationDialogPanel = new javax.swing.JPanel();
        yesButton = new javax.swing.JLabel();
        noButton = new javax.swing.JLabel();
        informationDialog = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information DIalog");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informationDialogPanel.setBackground(new java.awt.Color(255, 251, 209));
        informationDialogPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        informationDialogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/yes button (1).png"))); // NOI18N
        yesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        informationDialogPanel.add(yesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 230, 70));

        noButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/no button (1).png"))); // NOI18N
        informationDialogPanel.add(noButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 185, 230, 70));

        informationDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/information dialog (1).png"))); // NOI18N
        informationDialog.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                informationDialogMouseDragged(evt);
            }
        });
        informationDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                informationDialogMousePressed(evt);
            }
        });
        informationDialogPanel.add(informationDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 546, 296));

        getContentPane().add(informationDialogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void informationDialogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationDialogMousePressed
        // TODO add your handling code here:
        mouseDownCompCoords = evt.getPoint();
    }//GEN-LAST:event_informationDialogMousePressed

    private void informationDialogMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationDialogMouseDragged
        // TODO add your handling code here:
        Point currCoords = evt.getLocationOnScreen();
        setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
    }//GEN-LAST:event_informationDialogMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformationDialog(null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel informationDialog;
    private javax.swing.JPanel informationDialogPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noButton;
    private javax.swing.JLabel yesButton;
    // End of variables declaration//GEN-END:variables

}
